name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub
          
      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi, create_repo
          api = HfApi(token='$HF_TOKEN')
          try:
              create_repo('toobajatoi/emotion-detection', repo_type='space', space_sdk='gradio')
          except:
              pass
          api.upload_file(
              path_or_fileobj='emotion_dashboard.py',
              path_in_repo='app.py',
              repo_id='toobajatoi/emotion-detection',
              repo_type='space'
          )
          api.upload_file(
              path_or_fileobj='emotion_detector.py',
              path_in_repo='emotion_detector.py',
              repo_id='toobajatoi/emotion-detection',
              repo_type='space'
          )
          api.upload_file(
              path_or_fileobj='requirements.txt',
              path_in_repo='requirements.txt',
              repo_id='toobajatoi/emotion-detection',
              repo_type='space'
          )
          " 